on: [push]

name: build

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check system
        run: |
          lscpu && free -h

      - name: Run
        run: |
          curl -OL https://github.com/nats-io/nats-server/releases/download/v2.9.22/nats-server-v2.9.22-linux-amd64.tar.gz
          tar xvf nats-server-v2.9.22-linux-amd64.tar.gz
          ./nats-server-v2.9.22-linux-amd64/nats-server -js &
          bash scripts/run.sh

